[[redirects]]
from = "/*"
to = "/"
status = 200

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"

[build]
base = "frontend"
publish = "frontend/dist"
command = "npm run build"

[dev]
command = "php -S localhost:8080 -t backend"

