[[redirects]]
from = '/api/*'
to = '/.netlify/functions/server/:splat'
status = 200

[[headers]]
for = "/*"

[headers.values]
Access-Control-Allow-Origin = "*"

[build]
base = "frontend"
publish = "frontend/dist"
command = "npm run build"

[dev]
port = 8080
command = "php -S localhost:8080 -t backend"

